// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0B_B5AvtQMGYQT4YuRaVGPdFX5oGoXY',
    appId: '1:482868800647:web:4241bbe8526d66c83b1c22',
    messagingSenderId: '482868800647',
    projectId: 'stepsapp-4363e',
    authDomain: 'stepsapp-4363e.firebaseapp.com',
    storageBucket: 'stepsapp-4363e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilYKAGEfJBX1Sl1W_cmW4fNeoGUwPAKY',
    appId: '1:482868800647:android:a531fc6352d8d36c3b1c22',
    messagingSenderId: '482868800647',
    projectId: 'stepsapp-4363e',
    storageBucket: 'stepsapp-4363e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhERWq-o7nmxgF_BrG3Remvv6I-MM7U5o',
    appId: '1:482868800647:ios:140e1e0efe77c8bb3b1c22',
    messagingSenderId: '482868800647',
    projectId: 'stepsapp-4363e',
    storageBucket: 'stepsapp-4363e.firebasestorage.app',
    iosBundleId: 'com.example.testSteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhERWq-o7nmxgF_BrG3Remvv6I-MM7U5o',
    appId: '1:482868800647:ios:140e1e0efe77c8bb3b1c22',
    messagingSenderId: '482868800647',
    projectId: 'stepsapp-4363e',
    storageBucket: 'stepsapp-4363e.firebasestorage.app',
    iosBundleId: 'com.example.testSteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0B_B5AvtQMGYQT4YuRaVGPdFX5oGoXY',
    appId: '1:482868800647:web:e4f53de53bee68443b1c22',
    messagingSenderId: '482868800647',
    projectId: 'stepsapp-4363e',
    authDomain: 'stepsapp-4363e.firebaseapp.com',
    storageBucket: 'stepsapp-4363e.firebasestorage.app',
  );
}
